### ISSUE TITLE
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.

### ISSUE THREAD

**Issue by ismailismail** [murano500k/Internet-Radio-Player-Android#3]
Hi 
I am new to android development and  I could not run your app . When I open your project with android studio It says that "Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved"
How can I solve this issue

**Comment by murano500k** [comment]
Hi. It's because of dagger or butterknife version. Try to update these libs
or disable them. If disable, you need to remove any usage of this libs from
the app
