### ISSUE TITLE
Compared to such a problem

### ISSUE THREAD

**Issue by azizsan** [murano500k/Internet-Radio-Player-Android#4]
Compared to such a problem

Error:Execution failed for task ':app:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.core.JackToolchain$ToolchainException: Jack configuration exception.
  Property 'jack.import.type.policy' (in -D option): The value must be {keep-fırst,faıl} (case insensitive) but is 'keep-first'

**Comment by murano500k** [comment]
Pull changes, then try to rebuild. It should work
